lib/icd10cm_web/router.ex
defmodule Icd10cmWeb.Router do
  use Icd10cmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Icd10cmWeb do
    pipe_through :browser

    get("/", PageController, :index)

    get "/page", PageController, :index, as: :pages

    post("/icd10clinicals/search_clinicals", Icd10clinicalController, :search_clinicals)
    #resources("/icd10clinicals/search_clinicals", Icd10clinicalController, :search_clinicals)
    resources("/icd10clinicals", Icd10clinicalController)
    resources("/icd10cm_neoplasms", Icd10cm_neoplasmController)
    post("/icd10cm_neoplasms/search_neoplasms", Icd10cm_neoplasmController, :search_neoplasms)
    resources("/icd10cm_eindexes", Icd10cm_eindexController)
    post("/icd10cm_eindexes/search_eindexes", Icd10cm_eindexController, :search_eindexes)
    resources("/icd10cm_orders", Icd10cm_orderController)
    post("/icd10cm_orders/search_orders", Icd10cm_orderController, :search_orders)
    resources("/ctds", CtdController)
    post("/ctds/search_ctds", CtdController, :search_ctds)
    resources("/icd10cm_dindexes", Icd10cm_dindexController)
    post("/icd10cm_dindexes/search_dindexes", Icd10cm_dindexController, :search_dindexes)
    resources("/icd10_pcses", Icd10pcsController, as: :pcs)
    post("/icd10_pcses/search_pcs", Icd10pcsController, :search_pcs)
    resources("/icd10pcs_defs", Icd10pcs_defsController, as: :pcs_defs)
    post("/icd10pcs_defs/search_pcs_defs", Icd10pcs_defsController, :search_pcs_defs)
    resources("/Icd10cm_tree", Icd10cm_treeController, as: :icd10cm_tree)

    resources("/ndc_products", Ndc_productController) do
      resources("/ndc_packages", Ndc_packageController, as: :pack)
    end

    post("/ndc_products/search_ndc", Ndc_productController, :search_ndc)

    post(
      "/icd10cm_tree/get_icd10cm_clinicals_json",
      Icd10cm_treeController,
      :get_icd10cm_clinicals_json
    )
  end

  # Other scopes may use custom stacks.
  # scope "/api", Icd10cmWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Icd10cmWeb.Telemetry
    end
  end
end

lib/icd10cm/codes/icd10pcs_defs.ex
defmodule Icd10cm.Codes.Icd10pcs_defs do
  use Ecto.Schema
  import Ecto.Changeset

  schema "icd10pcs_defs" do
    field :axis_code, :string
    field :axis_title, :string
    field :section, :string
    field :section_title, :string
    field :term_definition, :string
    field :term_explanation, :string
    field :term_includes, :string
    field :term_titles, :string
    # field :terms, :string
    field :terms, :map
    field :title_tsv, :string
  end

  @doc false
  def changeset(icd10pcs_defs, attrs) do
    icd10pcs_defs
    |> cast(attrs, [
      :section,
      :section_title,
      :axis_code,
      :axis_title,
      :terms,
      :title_tsv,
      :term_definition,
      :term_explanation,
      :term_titles,
      :term_includes
    ])
    # |> validate_required([:section, :section_title, :axis_code, :axis_title, :terms, :title_tsv, :term_definition, :term_explanation, :term_titles, :term_includes])
    |> validate_required([])
  end
end

lib/icd10cm_web/controllers/icd10pcs_defs_controller.ex
defmodule Icd10cmWeb.Icd10pcs_defsController do
  use Icd10cmWeb, :controller

  alias Icd10cm.Codes
  alias Icd10cm.Codes.Icd10pcs_defs
  import Ecto.Query, warn: false

  plug(:scrub_params, "icd10_pcs_defs" when action in [:create, :update])

  def index(conn, params) do
    page =
      Codes.list_icd10pcs_defs(params)
      |> Icd10cm.Repo.paginate(page: params["page"], page_size: 30)

    render(conn, "index.html", icd10pcs_defs: page.entries, page: page)
    # icd10pcs_defs = Codes.list_icd10pcs_defs()
    # render(conn, "index.html", icd10pcs_defs: icd10pcs_defs)
  end

  def new(conn, _params) do
    changeset = Codes.change_icd10pcs_defs(%Icd10pcs_defs{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"icd10pcs_defs" => icd10pcs_defs_params}) do
    case Codes.create_icd10pcs_defs(icd10pcs_defs_params) do
      {:ok, icd10pcs_defs} ->
        conn
        |> put_flash(:info, "Icd10pcs defs created successfully.")
        |> redirect(to: Routes.icd10pcs_defs_path(conn, :show, icd10pcs_defs))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    icd10pcs_defs = Codes.get_icd10pcs_defs!(id)
    render(conn, "show.html", icd10pcs_defs: icd10pcs_defs)
  end

  def edit(conn, %{"id" => id}) do
    icd10pcs_defs = Codes.get_icd10pcs_defs!(id)
    changeset = Codes.change_icd10pcs_defs(icd10pcs_defs)
    render(conn, "edit.html", icd10pcs_defs: icd10pcs_defs, changeset: changeset)
  end

  def update(conn, %{"id" => id, "icd10pcs_defs" => icd10pcs_defs_params}) do
    icd10pcs_defs = Codes.get_icd10pcs_defs!(id)

    case Codes.update_icd10pcs_defs(icd10pcs_defs, icd10pcs_defs_params) do
      {:ok, icd10pcs_defs} ->
        conn
        |> put_flash(:info, "Icd10pcs defs updated successfully.")
        |> redirect(to: Routes.icd10pcs_defs_path(conn, :show, icd10pcs_defs))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", icd10pcs_defs: icd10pcs_defs, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    icd10pcs_defs = Codes.get_icd10pcs_defs!(id)
    {:ok, _icd10pcs_defs} = Codes.delete_icd10pcs_defs(icd10pcs_defs)

    conn
    |> put_flash(:info, "Icd10pcs defs deleted successfully.")
    |> redirect(to: Routes.icd10pcs_defs_path(conn, :index))
  end

  ##########################
  def search_pcs_defs(
        conn,
        %{"search_pcs_defs" => %{"query" => query, "selection" => selection}} = params
      ) do
    trim_query = String.trim(query)

    page =
      Icd10cm.Codes.search_pcs_defs(trim_query, selection)
      |> Icd10cm.Repo.paginate(page: params["page"], page_size: 800)

    render(conn, "index.html", icd10pcs_defs: page.entries, page: page)
  end

  # post("/icd10pcs_defs/search_pcs_defs", Icd10pcs_defsController, :search_pcs_defs)
  ################################ 3
end

lib/icd10cm_web/views/icd10pcs_defs_view.ex
defmodule Icd10cmWeb.Icd10pcs_defsView do
  use Icd10cmWeb, :view
  import Scrivener.HTML
end

lib/icd10cm_web/templates/icd10pcs_defs/edit.html.eex
<h1>Edit Icd10pcs defs</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.icd10pcs_defs_path(@conn, :update, @icd10pcs_defs)) %>

<span><%= link "Back", to: Routes.icd10pcs_defs_path(@conn, :index) %></span>

lib/icd10cm_web/templates/icd10pcs_defs/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :section %>
  <%= text_input f, :section %>
  <%= error_tag f, :section %>

  <%= label f, :section_title %>
  <%= text_input f, :section_title %>
  <%= error_tag f, :section_title %>

  <%= label f, :axis_code %>
  <%= text_input f, :axis_code %>
  <%= error_tag f, :axis_code %>

  <%= label f, :axis_title %>
  <%= text_input f, :axis_title %>
  <%= error_tag f, :axis_title %>

  <%= label f, :terms %>
  <%= textarea f, :terms %>
  <%= error_tag f, :terms %>

  <%= label f, :title_tsv %>
  <%= text_input f, :title_tsv %>
  <%= error_tag f, :title_tsv %>

  <%= label f, :term_definition %>
  <%= textarea f, :term_definition %>
  <%= error_tag f, :term_definition %>

  <%= label f, :term_explanation %>
  <%= textarea f, :term_explanation %>
  <%= error_tag f, :term_explanation %>

  <%= label f, :term_titles %>
  <%= textarea f, :term_titles %>
  <%= error_tag f, :term_titles %>

  <%= label f, :term_includes %>
  <%= textarea f, :term_includes %>
  <%= error_tag f, :term_includes %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/icd10cm_web/templates/icd10pcs_defs/index.html.eex
<% alias Icd10cm.Codes %>
<% alias Icd10cm.Repo %>

<div class="title_form">
<h4>Listing ICD-10-PCS Definitions</h4>
</div>
<!-------------search-------------------------------------->
<!-------------START SEARCH FORM-------------------------------------------->
<div class="search_form">
  <div class="large-6 medium-6 small-6 large-centered columns">
    <ul class="has-form">
               <%#= link "ICD-10-PCS", to: Routes.pcs_path(@conn, :index) %>
               <%= form_for @conn, Routes.icd10pcs_defs_path(@conn, :search_pcs_defs),
                   [as: :search_pcs_defs], fn f -> %>
            <div class="row collapse">
                <div class="large-4 small-9 columns">
                    <%=  select(f, :selection,
                        ["Term Title": "term_title",
                        #"Only Description": "long_description",
                        #"Used Codes": "codes_2",

                        ],
                        prompt: "---Select---",   required: true,
                        class: "form-control f-dropdown"  ) %>
                </div><!--large-8 small-9 columns-->

                <div class="large-6 medium-6 small-9 columns">
                    <%= text_input f, :query, placeholder: "Your Query",
                    class: "form-control ",
                    minLength: 4 %>
                </div><!--large-8 small-9 columns-->

                <div class="large-2 small-9 columns">
                    <%= submit "Search", class:  "button primary expanded"  %>

                </div><!--large-4 small-9 columns-->


            </div><!--row collapse-->


    <% end %>
             </ul>

      </div><!-- small-6 large-centered columns -->
</div>
</div><!--------search form----------------------->
<!-------------END SEARCH FORM-------------------------------------------->



<!-------------search-------------------------------------->

<table class="table responsive  stack table-scroll frame_1">
  <thead>
    <tr>
    <th>#</th>
     <th>Term titles</th>
      <th>Term definition</th>
      <th>Term explanation</th>
      <th>Term includes</th>
     
    </tr>
  </thead>

  <tbody>
   <%= for {icd10pcs_defs, index} <- Enum.with_index(@icd10pcs_defs) do %>
<%#= for icd10pcs_defs <- @icd10pcs_defs do %>
    <tr>
   <td> <%= index + 1  %></td>
    <td>
         <% term_titles = icd10pcs_defs.term_titles %> 
        <span style="color:#8000FF;"> 
        <i class="fa fa-stethoscope" aria-hidden="true"></i>
        </span>
        <%=  raw Codes.format_column(term_titles)%>
       <br/>
       <span style="color:gray;">
       Section: <%= icd10pcs_defs.section_title %>
       </span>
      </td>
        <td><em> <%= icd10pcs_defs.term_definition %> </em></td>
        <td><%= icd10pcs_defs.term_explanation %></td>
          <td>
           <% term_includes = icd10pcs_defs.term_includes %> 
           <span style="font-size:10px;">
          <%= raw Codes.format_column(term_includes) %>
          </span>
          
          </td>
   
    </tr>
<% end %>
  </tbody>
</table>
<div class="pagination text-center" role="navigation" aria-label="Pagination">
     <%= pagination_links @page %>
    </div>
<span><%#= link "New Icd10pcs defs", to: Routes.icd10pcs_defs_path(@conn, :new) %></span>

lib/icd10cm_web/templates/icd10pcs_defs/new.html.eex
<h1>New Icd10pcs defs</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.icd10pcs_defs_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.icd10pcs_defs_path(@conn, :index) %></span>

lib/icd10cm_web/templates/icd10pcs_defs/show.html.eex
<h1>Show Icd10pcs defs</h1>

<ul>

  <li>
    <strong>Section:</strong>
    <%= @icd10pcs_defs.section %>
  </li>

  <li>
    <strong>Section title:</strong>
    <%= @icd10pcs_defs.section_title %>
  </li>

  <li>
    <strong>Axis code:</strong>
    <%= @icd10pcs_defs.axis_code %>
  </li>

  <li>
    <strong>Axis title:</strong>
    <%= @icd10pcs_defs.axis_title %>
  </li>

  <li>
    <strong>Terms:</strong>
    <%= @icd10pcs_defs.terms %>
  </li>

  <li>
    <strong>Title tsv:</strong>
    <%= @icd10pcs_defs.title_tsv %>
  </li>

  <li>
    <strong>Term definition:</strong>
    <%= @icd10pcs_defs.term_definition %>
  </li>

  <li>
    <strong>Term explanation:</strong>
    <%= @icd10pcs_defs.term_explanation %>
  </li>

  <li>
    <strong>Term titles:</strong>
    <%= @icd10pcs_defs.term_titles %>
  </li>

  <li>
    <strong>Term includes:</strong>
    <%= @icd10pcs_defs.term_includes %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.icd10pcs_defs_path(@conn, :edit, @icd10pcs_defs) %></span>
<span><%= link "Back", to: Routes.icd10pcs_defs_path(@conn, :index) %></span>