lib/icd10cm_web/router.ex
defmodule Icd10cmWeb.Router do
  use Icd10cmWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Icd10cmWeb do
    pipe_through :browser

    get("/", PageController, :index)

    get "/page", PageController, :index, as: :pages

    post("/icd10clinicals/search_clinicals", Icd10clinicalController, :search_clinicals)
    #resources("/icd10clinicals/search_clinicals", Icd10clinicalController, :search_clinicals)
    resources("/icd10clinicals", Icd10clinicalController)
    resources("/icd10cm_neoplasms", Icd10cm_neoplasmController)
    post("/icd10cm_neoplasms/search_neoplasms", Icd10cm_neoplasmController, :search_neoplasms)
    resources("/icd10cm_eindexes", Icd10cm_eindexController)
    post("/icd10cm_eindexes/search_eindexes", Icd10cm_eindexController, :search_eindexes)
    resources("/icd10cm_orders", Icd10cm_orderController)
    post("/icd10cm_orders/search_orders", Icd10cm_orderController, :search_orders)
    resources("/ctds", CtdController)
    post("/ctds/search_ctds", CtdController, :search_ctds)
    resources("/icd10cm_dindexes", Icd10cm_dindexController)
    post("/icd10cm_dindexes/search_dindexes", Icd10cm_dindexController, :search_dindexes)
    resources("/icd10_pcses", Icd10pcsController, as: :pcs)
    post("/icd10_pcses/search_pcs", Icd10pcsController, :search_pcs)
    resources("/icd10pcs_defs", Icd10pcs_defsController, as: :pcs_defs)
    post("/icd10pcs_defs/search_pcs_defs", Icd10pcs_defsController, :search_pcs_defs)
    resources("/Icd10cm_tree", Icd10cm_treeController, as: :icd10cm_tree)

    resources("/ndc_products", Ndc_productController) do
      resources("/ndc_packages", Ndc_packageController, as: :pack)
    end

    post("/ndc_products/search_ndc", Ndc_productController, :search_ndc)

    post(
      "/icd10cm_tree/get_icd10cm_clinicals_json",
      Icd10cm_treeController,
      :get_icd10cm_clinicals_json
    )
  end

  # Other scopes may use custom stacks.
  # scope "/api", Icd10cmWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: Icd10cmWeb.Telemetry
    end
  end
end

lib/icd10cm/codes/ndc_package.ex
defmodule Icd10cm.Codes.Ndc_package do
  use Ecto.Schema
  import Ecto.Changeset

  schema "ndc_packages" do
    field :endmarketingdate, :string
    field :ndc_exclude_flag, :string
    field :ndcpackagecode, :string
    field :packagedescription, :string
    field :productid, :string
    field :productndc, :string
    field :sample_package, :string
    field :startmarketingdate, :string
    # field :ndc_pruduct_id, :integer

    # timestamps()
  end

  @doc false
  def changeset(ndc_package, attrs) do
    ndc_package
    |> cast(attrs, [
      :productid,
      :productndc,
      :ndcpackagecode,
      :packagedescription,
      :startmarketingdate,
      :endmarketingdate,
      :ndc_exclude_flag,
      # :ndc_pruduct_id,
      :sample_package
    ])

    # |> validate_required([:productid, :productndc, :ndcpackagecode, :packagedescription, :startmarketingdate, :endmarketingdate, :ndc_exclude_flag, :sample_package])
  end
end

lib/icd10cm_web/controllers/ndc_package_controller.ex
defmodule Icd10cmWeb.Ndc_packageController do
  use Icd10cmWeb, :controller

  alias Icd10cm.Codes
  alias Icd10cm.Codes.Ndc_package
  alias Icd10cm.Codes.Ndc_product

  alias Icd10cm.Repo

  plug(:assign_ndc_products)

  def index(conn, _params) do
    ndc_packages = Codes.list_ndc_packages(conn)
    render(conn, "index.html", ndc_packages: ndc_packages)
  end

  def new(conn, _params) do
    changeset = Codes.change_ndc_package(%Ndc_package{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"ndc_package" => ndc_package_params}) do
    case Codes.create_ndc_package(ndc_package_params) do
      {:ok, ndc_package} ->
        conn
        |> put_flash(:info, "Ndc package created successfully.")

      # |> redirect(to: Routes.ndc_product_pack_path(conn, :show, ndc_package))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    ndc_package = Codes.get_ndc_package!(id)
    render(conn, "show.html", ndc_package: ndc_package)
  end

  def edit(conn, %{"id" => id}) do
    ndc_package = Codes.get_ndc_package!(id)
    changeset = Codes.change_ndc_package(ndc_package)
    render(conn, "edit.html", ndc_package: ndc_package, changeset: changeset)
  end

  def update(conn, %{"id" => id, "ndc_package" => ndc_package_params}) do
    ndc_package = Codes.get_ndc_package!(id)

    case Codes.update_ndc_package(ndc_package, ndc_package_params) do
      {:ok, ndc_package} ->
        conn
        |> put_flash(:info, "Ndc package updated successfully.")
        |> redirect(to: Routes.ndc_product_pack_path(conn, :show, ndc_package))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", ndc_package: ndc_package, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    ndc_package = Codes.get_ndc_package!(id)
    # {:ok, _ndc_package} = Codes.delete_ndc_package(,ndc_package)

    conn
    |> put_flash(:info, "Ndc package deleted successfully.")

    # |> redirect(to: Routes.ndc_product_pack_path(conn, :index))
  end

  ############################### 333
  def assign_ndc_products(conn, _opts) do
    case conn.params do
      %{"ndc_product_id" => ndc_product_id} ->
        case Repo.get(Ndc_product, ndc_product_id) do
          ndc_product ->
            # IO.puts("---------------------------------------------------------" )
            # IO.inspect ndc_product
            assign(conn, :ndc_product, ndc_product)
        end

      _ ->
        conn
        |> send_resp(404, "NDC PRODUCT  Not Found")
        |> halt()
    end
  end

  ######################################
end

lib/icd10cm_web/views/ndc_package_view.ex
defmodule Icd10cmWeb.Ndc_packageView do
  use Icd10cmWeb, :view
end

lib/icd10cm_web/templates/ndc_package/edit.html.eex
<h1>Edit Ndc package</h1>

<%#= render "form.html", Map.put(assigns, :action, Routes.ndc_package_path(@conn, :update, @ndc_package)) %>

<span><%#= link "Back", to: Routes.ndc_package_path(@conn, :index) %></span>

lib/icd10cm_web/templates/ndc_package/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :productid %>
  <%= textarea f, :productid %>
  <%= error_tag f, :productid %>

  <%= label f, :productndc %>
  <%= textarea f, :productndc %>
  <%= error_tag f, :productndc %>

  <%= label f, :ndcpackagecode %>
  <%= textarea f, :ndcpackagecode %>
  <%= error_tag f, :ndcpackagecode %>

  <%= label f, :packagedescription %>
  <%= textarea f, :packagedescription %>
  <%= error_tag f, :packagedescription %>

  <%= label f, :startmarketingdate %>
  <%= textarea f, :startmarketingdate %>
  <%= error_tag f, :startmarketingdate %>

  <%= label f, :endmarketingdate %>
  <%= textarea f, :endmarketingdate %>
  <%= error_tag f, :endmarketingdate %>

  <%= label f, :ndc_exclude_flag %>
  <%= textarea f, :ndc_exclude_flag %>
  <%= error_tag f, :ndc_exclude_flag %>

  <%= label f, :sample_package %>
  <%= textarea f, :sample_package %>
  <%= error_tag f, :sample_package %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/icd10cm_web/templates/ndc_package/index.html.eex
<h1>Listing Ndc packages</h1>

<table>
  <thead>
    <tr>
      <th>Productid</th>
      <th>Productndc</th>
      <th>Ndcpackagecode</th>
      <th>Packagedescription</th>
      <th>Startmarketingdate</th>
      <th>Endmarketingdate</th>
      <th>Ndc exclude flag</th>
      <th>Sample package</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for ndc_package <- @ndc_packages do %>
    <tr>
      <td><%= ndc_package.productid %></td>
      <td><%= ndc_package.productndc %></td>
      <td><%= ndc_package.ndcpackagecode %></td>
      <td><%= ndc_package.packagedescription %></td>
      <td><%= ndc_package.startmarketingdate %></td>
      <td><%= ndc_package.endmarketingdate %></td>
      <td><%= ndc_package.ndc_exclude_flag %></td>
      <td><%= ndc_package.sample_package %></td>

      <td>
        <span><%#= link "Show", to: Routes.ndc_package_path(@conn, :show, ndc_package) %></span>
        <span><%#= link "Edit", to: Routes.ndc_package_path(@conn, :edit, ndc_package) %></span>
        <span><%#= link "Delete", to: Routes.ndc_package_path(@conn, :delete, ndc_package), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%#= link "New Ndc package", to: Routes.ndc_package_path(@conn, :new) %></span>

lib/icd10cm_web/templates/ndc_package/new.html.eex
<h1>New Ndc package</h1>

<%#= render "form.html", Map.put(assigns, :action, Routes.ndc_package_path(@conn, :create)) %>

<span><%#= link "Back", to: Routes.ndc_package_path(@conn, :index) %></span>

lib/icd10cm_web/templates/ndc_package/show.html.eex
<h1>Show Ndc package</h1>

<ul>

  <li>
    <strong>Productid:</strong>
    <%= @ndc_package.productid %>
  </li>

  <li>
    <strong>Productndc:</strong>
    <%= @ndc_package.productndc %>
  </li>

  <li>
    <strong>Ndcpackagecode:</strong>
    <%= @ndc_package.ndcpackagecode %>
  </li>

  <li>
    <strong>Packagedescription:</strong>
    <%= @ndc_package.packagedescription %>
  </li>

  <li>
    <strong>Startmarketingdate:</strong>
    <%= @ndc_package.startmarketingdate %>
  </li>

  <li>
    <strong>Endmarketingdate:</strong>
    <%= @ndc_package.endmarketingdate %>
  </li>

  <li>
    <strong>Ndc exclude flag:</strong>
    <%= @ndc_package.ndc_exclude_flag %>
  </li>

  <li>
    <strong>Sample package:</strong>
    <%= @ndc_package.sample_package %>
  </li>

</ul>

<span><%#= link "Edit", to: Routes.ndc_package_path(@conn, :edit, @ndc_package) %></span>
<span><%#= link "Back", to: Routes.ndc_product_pack_path(@conn, :index) %></span>